apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  namespace: mysql
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/volume   #path in your machine storage
