apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
  labels:
    app: mysql
type: Opaque    # user-defined info and let k8s to translate it
data:
  MYSQL_PASSWORD: bXlwYXNzd29yZAo=  #encrypted password
